class InstantiateCSVError(Exception):

    def __init__(self):
        print("Файл item.csv поврежден")
